config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /vi|en/ do
    namespace :admin do
      root "admin_static_pages#home"
      get "/home", to: "admin_static_pages#home"
      resources :products
    end

    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid

  has_many :products, dependent: :destroy

  validates :name, presence: true,
            length: {maximum: Settings.category.max_length}
end

app/models/order.rb
class Order < ApplicationRecord
  acts_as_paranoid

  belongs_to :user
  has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  acts_as_paranoid

  belongs_to :order
  belongs_to :product

  validates :quantity, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid

  belongs_to :category
  has_many :order_items, dependent: :destroy

  has_one_attached :image

  PRODUCT_ATTRIBUTE = [:name, :image, :description, :unit_price,
                       :is_discontinued, :is_featured, :category_id].freeze

  validates :name, presence: true,
            length: {maximum: Settings.product.name.max_length}

  validates :description,
            length: {maximum: Settings.product.description.max_length}

  validates :image, presence: true,
            content_type: {in: Settings.product.image.image_path,
                           message: :wrong_format},
            size: {less_than: Settings.product.image.less_than.megabytes,
                   message: :too_big}
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid

  has_many :orders, dependent: :destroy

  VALID_EMAIL_REGEX = Settings.user.email_regex
  validates :email, presence: true,
            length: {maximum: Settings.user.email.max_length},
            format: {with: VALID_EMAIL_REGEX},
            uniqueness: true

  validates :password, presence: true,
            length: {minimum: Settings.user.password.min_length},
            if: :password,
            allow_nil: true

  has_secure_password

  before_save :downcase_email

  class << self
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end
  end

  private
  def downcase_email
    email.downcase!
  end
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  layout "admin/layouts/application"
end

app/controllers/admin/admin_static_pages_controller.rb
class Admin::AdminStaticPagesController < Admin::AdminController
  before_action :check_login?

  def home; end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::AdminController
  before_action :check_login?

  def index
    @pagy, @products = pagy Product.all, items: Settings.product.items
  end

  def new
    @categories = Category.all
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".flash_success"
      redirect_to admin_products_path
    else
      flash[:danger] = t ".flash_danger"
      @categories = Category.all
      render :new
    end
  end

  private
  def product_params
    params.require(:product).permit(Product::PRODUCT_ATTRIBUTE)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  include Pagy::Backend

  before_action :set_locale

  private
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      check_role user
    else
      flash[:danger] = t ".flash_danger"
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_path
  end

  private
  def check_role user
    if user.admin
      log_in user
      flash[:success] = t ".flash_success"
      redirect_to admin_root_path
    else
      # redirect to client page
      # TODO
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def full_title page_title = ""
    base_title = t "app_name"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def check_login?
    return if logged_in?

    redirect_to login_path
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/admin/admin_static_pages/home.html.erb
<!-- TODO -->
<% provide :title, "Home" %>
<h1>AdminStaticPages#home</h1>
<p>Find me in app/views/admin_static_pages/home.html.erb</p>

app/views/admin/layouts/_admin_page.html.erb
<% if logged_in? %>
  <header class="float-right">
    <nav class="navbar navbar-light bg-white shadow-sm">
      <div class="navbar-collapse">
        <ul class="nav justify-content-end px-5">
          <li class="nav-item dropdown">
            <%= link_to "#", class: "dropdown-toggle nav-link h4", "role": "button", "data-toggle": "dropdown", "aria-expanded": "false" do %>
              <%= current_user.name %>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".log_out"), logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <div class="sidebar bg-primary shadow">
    <ul class="nav flex-column">
      <li class="shadow-sm">
        <%= link_to t("app_name"), admin_root_path, class: "nav-link logo text-white h1" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".home"), admin_root_path, class: "nav-link h4 bg-primary text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".category"), "#", class: "nav-link h4 bg-primary text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".product"), admin_products_path, class: "nav-link h4 bg-primary text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".user"), "#", class: "nav-link h4 bg-primary text-white" %>
      </li>
    </ul>
  </div>

  <div class="content">
    <div class="container-fluid">
      <div class="row mt-4 mb-3 mx-4">
        <div class="col-md-12">
          <% flash.each do |message_type, message| %>
            <div class="alert alert-<%= message_type %>" role="alert"><%= message %></div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </div>
<% else %>
  <%= render "sessions/login_page" %>
<% end %>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body class="bg-light">
    <%= render "admin/layouts/admin_page" %>
  </body>
</html>

app/views/admin/products/_form.html.erb
<%= form_for @product, :url => {:controller => "products"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :name, t(".name") %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :category_id, t(".category") %>
      <%= collection_select(:product, :category_id, @categories, :id, :name, {}, {class: "form-control"}) %>
    </div>
    <div class="form-group col-md-12">
      <%= f.label :description, t(".description") %>
      <%= f.text_area :description, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :image, t(".image") %>
      <div class="input-group">
        <div class="custom-file">
          <%= f.file_field :image, class: "form-control", id: "inputGroupFile01", "aria-describedby": "inputGroupFileAddon01" %>
          <label class="custom-file-label" for="inputGroupFile01"><%= t ".choose_file" %></label>
        </div>
      </div>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :unit_price, t(".unit_price") %>
      <div class="input-group">
        <%= f.number_field :unit_price, class: "form-control" %>
        <div class="input-group-append">
          <span class="input-group-text"><%= t ".denominations" %></span>
        </div>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="form-check">
        <%= f.check_box :is_discontinued, class: "form-check-input" %>
        <%= f.label :is_discontinued, t(".discontinued"), class: "form-check-label" %>
      </div>
    </div>
    <div class="form-group col-md-6">
      <div class="form-check">
        <%= f.check_box :is_featured, class: "form-check-input" %>
        <%= f.label :is_featured, t(".featured"), class: "form-check-label" %>
      </div>
    </div>
  </div>
  <%= f.submit t(".btn_add"), class: "btn btn-primary" %>
<% end %>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td>
    <% if product.image.attached? %>
    <%= image_tag product.image, class: "img-150" %>
    <% end %>
  </td>
  <td><%= product.unit_price %> <%= t ".denominations" %></td>
  <td><%= product.category.name %></td>
  <td><input type="checkbox" <% if product.is_discontinued %>checked<% end %> disabled></td>
  <td><input type="checkbox" <% if product.is_featured %>checked<% end %> disabled></td>
  <td>
    <%= link_to t(".btn_edit"), "#", class: "btn btn-primary" %>
    <%= link_to t(".btn_delete"), "#", class: "btn btn-danger" %>
  </td>
</tr>

app/views/admin/products/index.html.erb
<% provide :title, t(".title_page") %>
<div class="row mt-2 mb-5 mx-4">
  <div class="col-md-12">
    <div class="card shadow">
      <div class="card-header d-flex justify-content-between align-center">
        <h1><%= t ".title" %></h1>
        <div>
          <%= link_to t(".btn_add"), new_admin_product_path, class: "btn btn-success" %>
        </div>
      </div>
      <div class="card-body pt-0 pb-2">
        <table class="table">
          <thead>
            <tr>
              <th><%= t ".tbl_no" %></th>
              <th><%= t ".tbl_name" %></th>
              <th><%= t ".tbl_desciption" %></th>
              <th><%= t ".tbl_image" %></th>
              <th><%= t ".tbl_price" %></th>
              <th><%= t ".tbl_category" %></th>
              <th><%= t ".tbl_continue" %></th>
              <th><%= t ".tbl_feature" %></th>
              <th><%= t ".tbl_action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "product", collection: @products %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<% provide :title, t(".title_page") %>
<div class="row mt-2 mb-5 mx-4">
  <div class="col-md-12">
    <div class="card shadow">
      <div class="card-header">
        <h1><%= t ".title" %></h1>
      </div>
      <div class="card-body">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_admin_page.html.erb
<% if logged_in? %>
  <header class="float-right">
    <nav class="navbar navbar-light bg-white shadow-sm">
      <div class="navbar-collapse">
        <ul class="nav justify-content-end px-5">
          <li class="nav-item dropdown">
            <%= link_to "#", class: "dropdown-toggle nav-link h4", "role": "button", "data-toggle": "dropdown", "aria-expanded": "false" do %>
              <%= current_user.name %>
            <% end %>
            <ul class="dropdown-menu">
              <li><%= link_to t(".log_out"), logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        </ul>
      </div>
    </nav>
  </header>

  <div class="sidebar bg-primary shadow">
    <ul class="nav flex-column">
      <li class="shadow-sm">
        <%= link_to t("app_name"), "home", class: "nav-link logo text-white h1" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".home"), "home", class: "nav-link h4 bg-primary text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".category"), "#", class: "nav-link h4 bg-primary text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".product"), "products", class: "nav-link h4 bg-primary text-white" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".user"), "#", class: "nav-link h4 bg-primary text-white" %>
      </li>
    </ul>
  </div>

  <div class="content">
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
<% else %>
  <%= render "sessions/login_page" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body class="bg-light">
    <!-- Phan nay em se check user xem co phai admin khong. neu phai thi render admin page, con neu khong thi render client page -->
    <%= render "layouts/admin_page" %>
  </body>
</html>

app/views/products/_product.html.erb
<tr>
  <td><%= product.id %></td>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><img src="product.image" class="img-150"></td>
  <td><%= product.unit_price %> <%= t ".denominations" %></td>
  <td><%= product.category.name %></td>
  <td><input type="checkbox" <% if product.is_discontinued %>checked<% end %> disabled></td>
  <td><input type="checkbox" <% if product.is_featured %>checked<% end %> disabled></td>
  <td>
    <%= link_to t(".btn_edit"), "#", class: "btn btn-primary" %>
    <%= link_to t(".btn_delete"), "#", class: "btn btn-danger" %>
  </td>
</tr>

app/views/products/index.html.erb
<% provide :title, t(".title_page") %>
<div class="row my-5 mx-4">
  <div class="col-md-12">
    <div class="card shadow">
      <div class="card-header d-flex justify-content-between align-center">
        <h1><%= t ".title" %></h1>
        <div>
          <%= link_to t(".btn_add"), "#", class: "btn btn-success" %>
        </div>
      </div>
      <div class="card-body pt-0 pb-2">
        <table class="table">
          <thead>
            <tr>
              <th><%= t ".tbl_no" %></th>
              <th><%= t ".tbl_name" %></th>
              <th><%= t ".tbl_desciption" %></th>
              <th><%= t ".tbl_image" %></th>
              <th><%= t ".tbl_price" %></th>
              <th><%= t ".tbl_category" %></th>
              <th><%= t ".tbl_continue" %></th>
              <th><%= t ".tbl_feature" %></th>
              <th><%= t ".tbl_action" %></th>
            </tr>
          </thead>
          <tbody>
            <%= render partial: "product", collection: @products %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %> <%= pluralize object.errors.count, t(".error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>